name: finances
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
isar_version: &isar_version ^3.1.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  intl: ^0.18.1
  isar: *isar_version
  path_provider: ^2.0.15
  isar_flutter_libs: *isar_version
  popover: ^0.2.8+2
  tap_builder: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  isar_generator: *isar_version
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  change_app_package_name: ^1.1.0

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
  uses-material-design: true